<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>DeeKayBee</title><link rel=stylesheet href=/css/style.css><link rel=stylesheet href=/css/syntax.css><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel=stylesheet><link rel=preconnect href=https://fonts.googleapis.com><link rel=preconnect href=https://fonts.gstatic.com crossorigin><link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel=stylesheet></head><body><div class=container><header><h1 class=site-title>DeeKayBee</h1></header><nav><a href=/>Home</a>
<a href=/about>About</a>
<a href=/projects>Projects</a>
<a href=/cv>CV</a>
<a href=/contact>Contact</a></nav><main><section class=notes><h1>Python_pc_setup_II</h1><h2 id=install-the-python-binary>Install the Python binary</h2><p>Install the Python binary you want to work with if not already installed.
So for example the last binary I needed to install was the latest Python 3 for windows.
The version was:
<code>Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10)</code>.</p><p>The default installation location of Python is in the users folder. So it was installed in <code>%USERPROFILE%\AppData\Local\Programs\Python\Python36-32</code></p><p>See <a href=https://docs.python.org/3/using/windows.html>https://docs.python.org/3/using/windows.html</a> for details.</p><h2 id=install-a-python-virtual-environment-using-venv>Install a Python virtual environment using venv</h2><p>The venv docs are here:
<a href=https://docs.python.org/3/library/venv.html>https://docs.python.org/3/library/venv.html</a></p><p>Example:</p><pre tabindex=0><code class=language-code data-lang=code>c:\Users\dlewis\AppData\Local\Programs\Python\Python36-32\python -m venv C:\David\Jup
</code></pre><p>Tip: if you user name has a space in you are going to need to use the & and bracket. e.g.</p><pre tabindex=0><code>&amp; (path with a space in)
</code></pre><h2 id=start-the-virtual-environment>Start the virtual environment</h2><p>You might need to change the ExecutionPolicy in PowerShell to allow the scripts to run:</p><pre tabindex=0><code class=language-code data-lang=code>Set-ExecutionPolicy RemoteSigned
</code></pre><h2 id=activate-virtual-environment>Activate virtual environment</h2><pre tabindex=0><code class=language-code data-lang=code>C:\David\Jup\Scripts\Activate.ps1
</code></pre><h2 id=install-jupyter-notebooks>Install Jupyter Notebooks</h2><p><a href=http://jupyter.readthedocs.io/en/latest/install.html>http://jupyter.readthedocs.io/en/latest/install.html</a></p><p>Check pip is up-to-date</p><pre tabindex=0><code>pip3 install --upgrade pip
</code></pre><h3 id=install-jupyter>Install Jupyter</h3><pre tabindex=0><code>pip3 install jupyter
</code></pre><h3 id=install-pandas-and-its-dependencies>Install pandas and it&rsquo;s dependencies</h3><pre tabindex=0><code>pip3 install pandas
</code></pre><h3 id=install-matplotlib>Install matplotlib:</h3><pre tabindex=0><code>pip3 install matplotlib
</code></pre><h3 id=to-install-scipy>To install scipy:</h3><ul><li>Download relevant wheel</li><li><a href=http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy>http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy</a></li><li>Put wheel in a folder</li></ul><p>Then install wheel with pip3:</p><pre tabindex=0><code>pip3 scipy-0.19.0-cp36-cp36m-win32.whl
</code></pre><h3 id=reinstall-numpy-because-it-is-missing-mkl>Reinstall numpy because it is missing mkl:</h3><p>Download relevant wheel:</p><ul><li><a href=http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy>http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy</a></li></ul><pre tabindex=0><code>pip3 uninstall numpy
</code></pre><pre tabindex=0><code>pip3 install numpy-1.12.1+mkl-cp36-cp36m-win32.whl
</code></pre><h3 id=install-nose-so-you-can-test-installation>Install nose so you can test installation</h3><pre tabindex=0><code>pip3 install nose
</code></pre><h2 id=test-installation>Test installation</h2><p>Start Python in shell.</p><pre tabindex=0><code>import scipy
scipy.test(&#39;full&#39;)
</code></pre><pre tabindex=0><code class=language-output data-lang=output>======================================================================
FAIL: test_decomp_update.TestQRdelete_F.test_delete_last_p_col
----------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;C:\David\Jup\lib\site-packages\nose\case.py&#34;, line 198, in runTest
    self.test(*self.arg)
  File &#34;C:\David\Jup\lib\site-packages\scipy\linalg\tests\test_decomp_update.py&#34;
, line 328, in test_delete_last_p_col
    assert_unitary(q1)
  File &#34;C:\David\Jup\lib\site-packages\scipy\linalg\tests\test_decomp_update.py&#34;
, line 21, in assert_unitary
    assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 1411, in as
sert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 796, in ass
ert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=2.38419e-07

(mismatch 1.3888888888888857%)
 x: array([[  1.000000e+00 +0.000000e+00j,  -4.097819e-08 +2.980232e-08j,
         -2.607703e-08 -1.490116e-08j,   5.587935e-09 -1.490116e-08j,
         -2.235174e-08 -1.862645e-08j,  -2.793968e-09 +2.887100e-08j,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],...
</code></pre><pre tabindex=0><code class=language-output data-lang=output>======================================================================
FAIL: test_orthogonal.test_roots_gegenbauer
----------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;C:\David\Jup\lib\site-packages\nose\case.py&#34;, line 198, in runTest
    self.test(*self.arg)
  File &#34;C:\David\Jup\lib\site-packages\scipy\special\tests\test_orthogonal.py&#34;,
line 504, in test_roots_gegenbauer
    vgq(rootf(0.1), evalf(0.1), weightf(0.1), -1., 1., 25, atol=1e-13)
  File &#34;C:\David\Jup\lib\site-packages\scipy\special\tests\test_orthogonal.py&#34;,
line 287, in verify_gauss_quad
    assert_allclose(vv, np.eye(N), rtol, atol)
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 1411, in as
sert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 796, in ass
ert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-15, atol=1e-13

(mismatch 5.760000000000005%)
 x: array([[  1.000000e+00,  -1.854755e-17,   7.310015e-14,  -7.627779e-17,
          7.238787e-14,   2.754201e-17,   7.247653e-14,   1.854543e-17,
          6.807551e-14,   1.468432e-16,   6.300386e-14,   3.789022e-16,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,...

----------------------------------------------------------------------
</code></pre><pre tabindex=0><code class=language-output data-lang=output>----------------------------------------------------------
Ran 25578 tests in 610.564s

FAILED (KNOWNFAIL=129, SKIP=2117, failures=2)
&lt;nose.result.TextTestResult run=25578 errors=0 failures=2&gt;
----------------------------------------------------------
</code></pre><pre tabindex=0><code class=language-code data-lang=code>import numpy
numpy.test(&#39;full&#39;)
</code></pre><pre tabindex=0><code class=language-output data-lang=output>======================================================================
FAIL: test_default (test_numeric.TestSeterr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;C:\David\Jup\lib\site-packages\numpy\core\tests\test_numeric.py&#34;, line 4
32, in test_default
    under=&#39;ignore&#39;,
AssertionError: {&#39;divide&#39;: &#39;warn&#39;, &#39;over&#39;: &#39;raise&#39;, &#39;under&#39;: &#39;ignore&#39;, &#39;invalid&#39;
: &#39;warn&#39;} != {&#39;divide&#39;: &#39;warn&#39;, &#39;invalid&#39;: &#39;warn&#39;, &#39;over&#39;: &#39;warn&#39;, &#39;under&#39;: &#39;ign
ore&#39;}
- {&#39;divide&#39;: &#39;warn&#39;, &#39;invalid&#39;: &#39;warn&#39;, &#39;over&#39;: &#39;raise&#39;, &#39;under&#39;: &#39;ignore&#39;}
?                                                 ^^^^

+ {&#39;divide&#39;: &#39;warn&#39;, &#39;invalid&#39;: &#39;warn&#39;, &#39;over&#39;: &#39;warn&#39;, &#39;under&#39;: &#39;ignore&#39;}
?                                                ++ ^


======================================================================
</code></pre><pre tabindex=0><code class=language-output data-lang=output>======================================================================
FAIL: test_io.test_load_refcount
----------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;C:\David\Jup\lib\site-packages\nose\case.py&#34;, line 198, in runTest
    self.test(*self.arg)
  File &#34;C:\David\Jup\lib\site-packages\numpy\lib\tests\test_io.py&#34;, line 2014, i
n test_load_refcount
    assert_(gc.isenabled())
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 110, in ass
ert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
</code></pre><pre tabindex=0><code class=language-output data-lang=output>======================================================================
FAIL: test_io.test_load_refcount
----------------------------------------------------------------------
Traceback (most recent call last):
  File &#34;C:\David\Jup\lib\site-packages\nose\case.py&#34;, line 198, in runTest
    self.test(*self.arg)
  File &#34;C:\David\Jup\lib\site-packages\numpy\lib\tests\test_io.py&#34;, line 2014, i
n test_load_refcount
    assert_(gc.isenabled())
  File &#34;C:\David\Jup\lib\site-packages\numpy\testing\utils.py&#34;, line 110, in ass
ert_
    raise AssertionError(smsg)
AssertionError

----------------------------------------------------------------------
</code></pre><h2 id=start-jupyter-notebook>Start Jupyter Notebook</h2><p>You might need to map a drive first:</p><pre tabindex=0><code>net use z: \\servername\users\username
</code></pre><p>Activate virtual environment:</p><pre tabindex=0><code class=language-code data-lang=code>C:\David\Jup\Scripts\Activate.ps1
</code></pre><p>Finally start the notebook.</p><pre tabindex=0><code>jupyter notebook
</code></pre><p>To stop the server <code>ctrl-C</code></p><p>To return ExecutionPolicy to the default safe level.</p><pre tabindex=0><code>Set-ExecutionPolicy Restricted
</code></pre></section></main><footer><small>Copyright 2022 Me.</small></footer><script src=dkb.js></script></div></body></html>